-- ============================================================
-- Parent-child linking tables
-- Run this in your Supabase SQL editor
-- ============================================================

-- Invite codes generated by students, claimed by parents
create table if not exists invite_codes (
  id          uuid primary key default gen_random_uuid(),
  code        text unique not null,
  student_id  uuid references profiles(id) on delete cascade not null,
  claimed     boolean not null default false,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null default (now() + interval '7 days')
);

create index if not exists invite_codes_code_idx       on invite_codes(code);
create index if not exists invite_codes_student_idx    on invite_codes(student_id);

alter table invite_codes enable row level security;

-- Students can create and view their own codes
create policy "Students manage their own codes"
  on invite_codes for all
  using (student_id = auth.uid())
  with check (student_id = auth.uid());

-- Anyone authenticated can read a code by its value (to claim it)
create policy "Authenticated users can read codes to claim"
  on invite_codes for select
  using (auth.role() = 'authenticated');

-- Parent-child links
create table if not exists parent_child_links (
  id          uuid primary key default gen_random_uuid(),
  parent_id   uuid references profiles(id) on delete cascade not null,
  child_id    uuid references profiles(id) on delete cascade not null,
  linked_at   timestamptz not null default now(),
  unique (parent_id, child_id)
);

create index if not exists parent_child_links_parent_idx on parent_child_links(parent_id);
create index if not exists parent_child_links_child_idx  on parent_child_links(child_id);

alter table parent_child_links enable row level security;

create policy "Parents view their own links"
  on parent_child_links for select
  using (parent_id = auth.uid());

create policy "Parents create links"
  on parent_child_links for insert
  with check (parent_id = auth.uid());

create policy "Students view links to them"
  on parent_child_links for select
  using (child_id = auth.uid());
